### ISSUE TITLE
Add community projects to Readme

### ISSUE THREAD

**Issue by alii** [Phineas/lanyard#10]
It would be nice to have community projects (e.g. [use-lanyard](https://www.npmjs.com/package/use-lanyard)) listed on the readme.

This could be a sticky issue and projects could be added in comments. Up for debate I guess

**Comment by Looskie** [comment]
YES ALISTAIR YES YES

**Comment by punctuations** [comment]
^ what @Looskie said

**Comment by punctuations** [comment]
hi Alistair, how are you

**Comment by Looskie** [comment]
hi Alistair, how are you

**Comment by Looskie** [comment]
thats good to here, im doing fine as well.

**Comment by alii** [comment]
ok

**Comment by punctuations** [comment]
> hi guys im doing great just woke up, how are u both

I'm good, I just got home, so, either of you up to anything cool recently?

**Comment by Phineas** [comment]
Done!
