### ISSUE TITLE
Showing Discord Presence 

### ISSUE THREAD

**Issue by Avyansh0001** [Phineas/lanyard#125]
How can I show my RPC on my website?  @Phineas

**Comment by dustinrouillard** [comment]
You should ask this question in the Lanyard discord in the support channel. Issues on this repo aren't really for that type of support.

However that depends on your site, if it's react you can use the hook Alistair made [use-lanyard](https://github.com/alii/use-lanyard)
If it's vanilla javascript and html, you can use something like [js-lanyard](https://github.com/xaronnn/js-lanyard) but there is plenty of options visible in the projects section of this Lanyards readme.
