### ISSUE TITLE
Error in Self Hosting

### ISSUE THREAD

**Issue by PHPxCODER** [Phineas/lanyard#144]
{"success":false,"error":{"message":"User is not being monitored by Lanyard","code":"user_not_monitored"}}

**Comment by Phineas** [comment]
This isn't a well written issue.

Are you in the same server as your bot?
Are there any errors in console?
Did you enable the Activity intent in the bot's settings?

**Comment by PHPxCODER** [comment]
The Bot is in The Same Server as I am & Activity Intent is also "On" !

Regarding The Errors in Console, It isnt able to Connect With My Redis Server Locally Hosted in Docker

Docker Command I Used : docker run --rm -it -p 4001:4001 -e REDIS_HOST=redis:latest -e BOT_TOKEN=tokenofmybot --link redis-6d3G phineas/lanyard:latest
This is My Redis String : redis://default:redispw@localhost:49153


Here is the error code while running the docker command

08:40:57.903 [info]  Discord bot running on #PID<0.1420.0>

08:40:58.367 [debug] Discord: Hello

08:40:58.707 [debug] Discord: Heartbeat ACK

08:41:02.909 [error] Task #PID<0.1431.0> started from #PID<0.1420.0> terminating
** (MatchError) no match of right hand side value: {:error, {{:badmatch, {:error, %Redix.ConnectionError{reason: :closed}}}, [{Lanyard.Connectivity.Redis, :hgetall, 1, [file: 'lib/connectivity/redis.ex', line: 92]}, {Lanyard.Presence, :init, 1, [file: 'lib/presence/presence.ex', line: 23]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
    (lanyard 0.1.0) lib/gateway/client.ex:316: anonymous fn/2 in Lanyard.Gateway.Client.create_member_presences/1
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.22764603/0 in Lanyard.Gateway.Client.create_member_presences/1>

**Comment by PHPxCODER** [comment]
> The Bot is in The Same Server as I am & Activity Intent is also "On" !
> 
> Regarding The Errors in Console, It isnt able to Connect With My Redis Server Locally Hosted in Docker
> 
> Docker Command I Used : docker run --rm -it -p 4001:4001 -e REDIS_HOST=redis:latest -e BOT_TOKEN=tokenofmybot --link redis-6d3G phineas/lanyard:latest This is My Redis String : redis://default:redispw@localhost:49153
> 
> Here is the error code while running the docker command
> 
> 08:40:57.903 [info] Discord bot running on #PID<0.1420.0>
> 
> 08:40:58.367 [debug] Discord: Hello
> 
> 08:40:58.707 [debug] Discord: Heartbeat ACK
> 
> 08:41:02.909 [error] Task #PID<0.1431.0> started from #PID<0.1420.0> terminating ** (MatchError) no match of right hand side value: {:error, {{:badmatch, {:error, %Redix.ConnectionError{reason: :closed}}}, [{Lanyard.Connectivity.Redis, :hgetall, 1, [file: 'lib/connectivity/redis.ex', line: 92]}, {Lanyard.Presence, :init, 1, [file: 'lib/presence/presence.ex', line: 23]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}} (lanyard 0.1.0) lib/gateway/client.ex:316: anonymous fn/2 in Lanyard.Gateway.Client.create_member_presences/1 (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2 (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2 (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 Function: #Function<0.22764603/0 in Lanyard.Gateway.Client.create_member_presences/1>

Issue Resolved When I Use docker-compose file, it wasn't able to connect to the Redis Server 
Thanks Phineas ✌
