### ISSUE TITLE
Needed help.

### ISSUE THREAD

**Issue by MemeZYT** [Phineas/lanyard#147]
Hello! 

Basically I have some problems with my website. 
At first, timestamps are not working correctly.
![image](https://user-images.githubusercontent.com/76597738/179364147-621d48d9-b89b-416d-9d53-07a156f90300.png)
And second. Song/video doesnt update some times
![image](https://user-images.githubusercontent.com/76597738/179364160-137789a7-589a-43da-8943-535072f5e040.png)
And finally. When presence doesnt have timestamp, console goes crazy.
![image](https://user-images.githubusercontent.com/76597738/179364182-4aa62fc1-16bf-4452-990e-f7f02cb66da7.png)

**Comment by dustinrouillard** [comment]
This is not a lanyard issue, you've already asked in the discord and received an answer sufficient to solve your issue.

Lanyard doesn't do any processing on the data. Just returns what discord gives us, the start and end timestamp need to be used for calculation, in the same way the discord client does.

In the case of both start and end timestamp existing, you calculate (end-start) and that's the how long in milliseconds that activity will be going on for, and from there you can do all kinds of things, like to get time till end of song take the current date milliseconds and subtract it from the end timestamp.

Closing this, as this is not a support channel for non-lanyard related bugs, this is with your implementation of the math, please try using discord again for this.
