### ISSUE TITLE
Discord Bots?

### ISSUE THREAD

**Issue by SX-9** [Phineas/lanyard#195]
Make it so that we can invite bots to the lanyard server (without permissions ofc) so that we can see if our bots is online or not

**Comment by dustinrouillard** [comment]
We already do this upon request, but we have no interest in automating this and it's not possible to give users the ability to invite bots.

**Comment by SX-9** [comment]
Why not make a channel for that?

**Comment by JustFossa** [comment]
I mean, if you want to see if the bot is online, you can just run it within ur backend or something, and then you are sure that when ur backend is on, your bot it aswell
