### ISSUE TITLE
New username system

### ISSUE THREAD

**Issue by amnezziaa** [Phineas/lanyard#209]
Hello, as you have probably seen already, usernames are [evolving](https://discord.com/blog/usernames) on discord. Therefore, the old way of displaying the `tag` will become obsolete (see image).

Are there any update planned to evolve according to these changes ?

I'm also mentionning that a [new badge](https://support.discord.com/hc/en-us/articles/12620128861463-New-Usernames-Display-Names#docs-internal-guid-0f4df147-7fff-285d-073f-5688681d6d30) has also appeared in relation to these changes so maybe it could be added as well.

##

<img width="290" alt="image" src="https://github.com/Phineas/lanyard/assets/94064103/3a770425-1547-4535-99f5-3ee467ab6c91">

**Comment by timcole** [comment]
This issue is invalid, lanyard just relays the user object from discord so automatically already handles the new username. From your screenshot you’re showing Conrad’s readme which uses lanyard. https://github.com/cnrad/lanyard-profile-readme Which does support hiding the discriminator.

**Comment by eggsy** [comment]
from the official discord server:

<img width="983" alt="image" src="https://github.com/Phineas/lanyard/assets/13917975/aaa87ccc-56e3-49bd-85f5-c4a4ef921bbe">

**Comment by amnezziaa** [comment]
I see, good that it already works then. Closing this now !
