### ISSUE TITLE
Implement new existing badges

### ISSUE THREAD

**Issue by Putt0** [Phineas/lanyard#234]
# List of some emblems ->

## Common Badges:

![image](https://github.com/Phineas/lanyard/assets/73148987/e762283d-e327-44cf-8a94-b958586f667c)
![image](https://github.com/Phineas/lanyard/assets/73148987/2f47ac7b-9864-4df7-a087-312df5e473fc)
![image](https://github.com/Phineas/lanyard/assets/73148987/384e332b-4b51-4105-9231-0ff2a2374b7e)

## Rare Badges:

![image](https://github.com/Phineas/lanyard/assets/73148987/f78fb006-ff5b-4859-95c7-893999364ef3)
![image](https://github.com/Phineas/lanyard/assets/73148987/e9830c45-b45c-4f3c-8b51-6d2d6ada38b7)
![image](https://github.com/Phineas/lanyard/assets/73148987/6b526c94-78bf-4d76-993f-3f064b653304)
![image](https://github.com/Phineas/lanyard/assets/73148987/7172ead4-edf9-4508-aaec-fa335d2ef836)

## Unobtainable Badges:

![image](https://github.com/Phineas/lanyard/assets/73148987/18dcbdd4-b9bc-4685-a662-040c98ad9bad)
![image](https://github.com/Phineas/lanyard/assets/73148987/4331918f-d217-4359-8498-7cb2f82440cd)
![image](https://github.com/Phineas/lanyard/assets/73148987/17ac3143-6839-4f44-bc11-b711b91add38)
![image](https://github.com/Phineas/lanyard/assets/73148987/89114be2-2a51-4593-8edf-9095683669cd)
![image](https://github.com/Phineas/lanyard/assets/73148987/7b03df1d-32f5-4b96-854c-f5e861bc5d72)

## Other Badges:

![image](https://github.com/Phineas/lanyard/assets/73148987/e4488f85-3a4d-46a1-ab43-f3bba36a3215)

# I ended up finding other emblems, but I don't know if it's real:

![image](https://github.com/Phineas/lanyard/assets/73148987/0e94e036-0921-4c08-aa18-5588d5ff86da)

# Source: https://discord.fandom.com/wiki/Badges

**Comment by SaTaNxYz** [comment]
@Putt0 It would be a great idea, but these emblems probably already exist.

**Comment by Piqque** [comment]
It would be a great idea!! maybe people will implement

**Comment by dustinrouillard** [comment]
Great idea, however this is not something Lanyard itself needs to do anything to implement, as we forward the data directly from discords gateway, so I'm gonna close this as it's not really an "issue".

If you use an integration that gets it data from the Lanyard API which doesn't support one or more of these badges, you should find the repo for it specifically (Likely it'll be listed in the projects section of the [readme](https://github.com/Phineas/lanyard/?tab=readme-ov-file#community-projects)) and contribute or give them feedback over there!
