### ISSUE TITLE
Support for fetching "set activity" type per each activity?

### ISSUE THREAD

**Issue by AkikoKumagara** [Phineas/lanyard#239]
This would be a nice feature since [setting activity type](https://x.com/advaithj1/status/1816655583107510517) is now supported in Discord RPC.

**Comment by dustinrouillard** [comment]
This should already be something you can get from the `activity.type`  parameter. It's an enum, `0` being playing, `2` being listening, etc. (Also anything discord sends down the gateway (websocket) will be in lanyard by default with no changes to lanyard, so things like thing just rely on them sending them down the realtime gateway)

https://discord.com/developers/docs/developer-tools/game-sdk#activitytype-enum

**Comment by AkikoKumagara** [comment]
Understood, thanks. Didn't realize I have to parse them myself rather than getting a text string output.
