### ISSUE TITLE
All Activities except Custom Status not properly being shown

### ISSUE THREAD

**Issue by jvqze** [Phineas/lanyard#243]
When playing an activity or even just playing Spotify on the application, it appears that Lanyard isn't catching my Discord Activities at all, just my Custom Status only.

Here's a working one
![opera_7nvCbg6poX](https://github.com/user-attachments/assets/afac1c43-a634-42fd-97de-4f89f3e76254)

And now here's a broken one (Provided By @bohd4nx)
![opera_F9jaUKtJoK](https://github.com/user-attachments/assets/ab5af2e3-9c09-436f-b86a-23fe13eb7764)
![Discord_7MyxcubP88](https://github.com/user-attachments/assets/f0d13833-4db0-42e4-b8ec-46a5f36a2f31)

**Comment by wont-stream** [comment]
Not sure why you felt the need to post both here and the support channel, there’s zero chance this is something internal so the support channel is the better place for this.

**Comment by jvqze** [comment]
Sorry for opening this, the issue was a "me" issue that accidentally had one of the Activity Privacy Disabled.
