### ISSUE TITLE
Discord Bio & Banner?

### ISSUE THREAD

**Issue by OfficialCRUGG** [Phineas/lanyard#50]
Hey there,
would it be possible to also put a user's bio and their banner on the User Endpoint?

**Comment by 5elenay** [comment]
## TL;DR;
You need to make a self-bot for that. Because discord does not gives banner hash or bio information for bots right now. Since self-bot is against ToS, lanyard probably will not have these features unless discord gives it.

## Links
[Endpoint For Profile](https://discord.com/api/v9/users/793467584820281346/profile?with_mutual_guilds=false)

**Comment by Phineas** [comment]
I do want to eventually support this, so will leave this issue open in case anyone has other ideas about how to go about it

**Comment by OfficialCRUGG** [comment]
> ## TL;DR;
> You need to make a self-bot for that. Because discord does not gives banner hash or bio information for bots right now. Since self-bot is against ToS, lanyard probably will not have these features unless discord gives it.
> 
> ## Links
> [Endpoint For Profile](https://discord.com/api/v9/users/793467584820281346/profile?with_mutual_guilds=false)

According to some folks on the discord.js Discord (I know, totally the best source for information) a couple of days ago, Discord said - somewhere - that Bots will soon be able to access banners, but bios are not planned.

**Comment by 5elenay** [comment]
Discord now gives banner information for bots when you fetch the user:
![image](https://user-images.githubusercontent.com/71087882/128901512-bb408436-52e2-4a88-9f23-71ef8e791f36.png)

But in websocket, They still don't added banner informations for user struct i think:
![image](https://user-images.githubusercontent.com/71087882/128901711-d126f2a9-a651-4b45-9a2e-33cd168862ac.png)

So maybe we can add a endpoint that fetches the user (this endpoint will not require to join the server.) but client can be rate limited when they spam. Any idea?

**Comment by Milo123459** [comment]
It's just a hash, how do we decode and render it?

**Comment by 5elenay** [comment]
> 
> 
> It's just a hash, how do we decode and render it?

`https://cdn.discordapp.com/banners/<user_id>/<hash>.<format>?size=<size>`

- `user_id`: The user id that owns the banner.
- `hash`: Banner hash. (its animated if hash starts with `a_`.)
- `format`: Image format for banner. like png, gif, jpg etc...
- `size`: Banner size. (discord uses `300` for mini-profile and `600` for profile.)

# Example
https://cdn.discordapp.com/banners/704758931343278162/9cb5914f1c4d912b4b85584551ecacd7.png?size=600

**Comment by Milo123459** [comment]
Oh of course, I thought you meant rendering it from the hash, not using the URL

**Comment by dustinrouillard** [comment]
I've got a CDN/API worker that I've been sharing in the discord for anyone who needs it, and it is reliable for banners/avatars since it uses a bot account in the server, however it does also have support for the entire user profile including the bio (should read the gist on this one though)

I have a gist detailing the routes and such here : https://dcdn.dstn.to/gist

**Comment by OfficialCRUGG** [comment]
> I've got a CDN/API worker that I've been sharing in the discord for anyone who needs it, and it is reliable for banners/avatars since it uses a bot account in the server, however it does also have support for the entire user profile including the bio (should read the gist on this one though)
> 
> 
> 
> I have a gist detailing the routes and such here : https://dcdn.dstn.to/gist
> 
> Example : https://dcdn.dstn.to/profile/156114103033790464

That looks interesting! Will have a look soon!

**Comment by Dodgers-Chino** [comment]
Clear : )

**Comment by Coder2195Text** [comment]
https://discordlookup.mesavirep.xyz/v1/user/604779545018761237
@mesalytic offers this discord lookup api if u wish for a nice API to integrate
https://github.com/mesalytic/discord-lookup-api

**Comment by codemikko** [comment]
It dosnt show the discord status though. In which, what does the discord_status label under anyways?

Also here is the full code I was using https://sourceb.in/R1nGgMPZzG

**Comment by seliim1337** [comment]
@Phineas I have a project that might be useful to you 
https://github.com/seliim1337/lanyard-test-web
